  print (75+58+1256) #EJ1

print(854*692*5) #EJ2

v=int(input("ingresa velocidad")) #EJ3
t=int(input("ingresa el tiempo"))
print("La distancia reccorrida es: ", v*t,"km/h")

print("ingresa tu año de nacimiento") #EJ4
a=int(input())
b=2024
c=b-a
print("edad: ",c)

print("Descuento de 20% en todos los jeans") #EJ5
j=int(input("Ingresa el precio original del jean: "))
d= j*20/100
p=j-d
print("El precio final es: $",p)

print("Ingrese un número") #EJ6
d=int(input())
a=30*d/100
b=60*d/100
c=90*d/100
print("El 30% de",d, "es: ",a)
print(   "El 60% es: ",b)
print(    "El 90% es: ", c)

print("¿Cuanto mide el primer lado?") #EJ7
a=int(input())
print("¿Cuánto mide el segundo lado?")
b=int(input())
print("El área de este cuadrado es: ",a*b,"cm²")  

print("                 CALCULAR PROMEDIO\n", "Ingresa 5 valores:\n") #EJ8

a=(input("1."))
b=(input("2."))
c=(input("3."))
d=(input("4."))
e=(input("5."))
print=inter("El promedio de estos es: ",(a*b*c*d*e/a+b+c+d+e))



